openapi: 3.0.3
info:
  title: Buyer Service - OpenAPI 3.0
  version: 1.0.0
externalDocs:
  description: Buyer Service draft spec swagger
  url: http://swagger.io
servers:
  - url: "https://proxy.qa.nocnoc-internal.com/buyer-service"
paths:
  /v1/user/quotation/summary:
    post:
      tags:
        - Quotation
      parameters:
       - name: x-nocnoc-platform
         in: header
         schema:
          type: string
       - name: x-nocnoc-device-os
         in: header
         schema:
          type: string
       - name: x-cookie-id
         in: header
         schema:
          type: string
       - name: x-session-id
         in: header
         schema: 
          type: string
       - name: x-nocnoc-device-id
         in: header
         description: device id generate from FE
         schema:
          type: string
       - name: x-request-id
         in: header
         schema:
          type: string
       - name: x-nocnoc-id
         in: header
         required: true
         description: nocnoc-id decrypt by local authorizer
         schema:
          type: string
      summary: Calculate price and discount
      description: Calculate price and discount for both product and shipping
      operationId: quotationSummary
      requestBody:
        description: Sum the final quotation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quotationSummaryRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quotationSummaryResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: Unauthorize
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/user/order:
    post:
      tags:
        - My Orders
      parameters:
        - name: x-nocnoc-platform
          in: header
          schema:
            type: string
        - name: x-nocnoc-device-os
          in: header
          schema:
           type: string
        - name: x-cookie-id
          in: header
          schema:
            type: string
        - name: x-session-id
          in: header
          schema: 
            type: string
        - name: x-nocnoc-device-id
          in: header
          description: device id generate from FE
          schema:
            type: string
        - name: x-request-id
          in: header
          schema:
            type: string
        - name: x-nocnoc-id
          in: header
          required: true
          description: nocnoc-id decrypt by local authorizer
          schema:
            type: string
        - name: CF-Request-ID
          in: header
          description: cloudflare request id
          schema:
            type: string
      summary: Get user order lists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userOrderListRequest'
        required: true
      responses: 
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userOrderListResponse'

      

components:
  schemas:
    baseQuotationRequest:
      type: object
      required:
        - quotationSignature
        - quotationData
      properties:
        quotationSignature:
          type: string
          example: hash HMAC
        quotationData:
          type: string
          example: BASE564
    promotionRequest:
      allOf:
        - $ref: '#/components/schemas/baseQuotationRequest'
      type: object
      properties:
        couponCodes:
          type: array
          items:
            type: string
    userOrderListRequest:
        type: object
        properties:
          lang:
            type: string
            example: th
          userType:
            type: string
            example: BUYER
            enum:
              - BUYER
              - ADMIN
          locale:
            type: string
            example: th
            enum:
              - th
              - en
          userId:
            type: number
            example: 10
          limit:
            type: number
            example: 10
          page:
            type: number
            example: 1
          tabType:
            type: string
            example: OPEN
          itemType:
            type: string
            example: sale-orders
          filter:
            type: object
            properties:
              searchTerm:
                type: string
              orderStatus:
                type: string
                example: PAYMENT_PENDING
    userOrderListResponse:
      type: object
      required:
        - status
        - data
      properties:
        status:
          type: string 
          example: SUCCESS
          enum:
            - SUCCESS
            - FAILED
        data:
          type: object
          properties:
            limit:
              type: number
              example: 10
            page:
              type: number
              example: 1
            tabType:
              type: string
              example: OPEN
            itemType:
              type: string
              example: sale-orders
            items:
              type: array
              items:
                $ref: '#/components/schemas/userOrderItem'
            cancellable:
              type: boolean
            extraInfo:
              $ref: '#components/schemas/userOrderExtraInfo'
        errors:
          type: object
          properties:
            code:
              type: string
              example: forbidden
            ref:
              type: string
            msg:
              type: string
    userOrderExtraInfo:
      type: object
      properties:
        statusFilter:
          $ref: '#/components/schemas/userOrderStatusFilter'
        cancelReason:
          $ref: '#/components/schemas/userOrderCancelReason'
    
    userOrderStatusFilter:
      type: object
      properties:
        field:
          type: string
          example: "orderStatus"
        options:
          type: array
          items:
            type: string
          example: 
            - "ALL_OPEN_STATUS"
            - "PAYMENT_PENDING"
            - "PAYMENT_EXPIRED"
            - "ON_HOLD"
            - "PLACED"
            - "ACCEPTED"
            - "READY_TO_SHIP"
            - "IN_TRANSIT"

    userOrderCancelReason:
      type: object
      properties:
        ALL:
          type: array
          items:
            $ref: '#/components/schemas/cancelReasonItem'

    cancelReasonItem:
      type: object
      properties:
        code:
          type: string
          example: "SELLER_REQUESTED_EXTEND_DELIVERY_TIME"
        text:
          type: string
          example: "Seller requested to extend the delivery time"
        sequence:
          type: integer
          example: 800
    userOrderItem:
      type: object
      properties:
        orderNo:
          type: string
          example: "NN-3D34HV3YLDSWV"
        userId:
          type: string
          example: "6565"
        orderPlacedDate:
          type: string
          nullable: true
          example: ""
        orderPlacedTime:
          type: string
          nullable: true
          example: ""
        totalAmount:
          type: string
          format: decimal
          example: "4000.00"
        billingAddress:
          type: string
          example: ""
        retryPaymentDueTime:
          type: integer
          format: int64
          example: 1722509062000000000
        deliveryAddress:
          $ref: '#/components/schemas/deliveryAddress'
        orderCanCancel:
          type: boolean
          example: true
        buyerCanCancelShipment:
          type: boolean
          example: true
        canRetryPay:
          type: boolean
          example: true
        paidOrder:
          type: boolean
          example: false
        paymentSlipUrl:
          type: string
          example: ""
        paymentReference:
          type: string
          format: uuid
          example: "543f1881-688d-4b4c-9ce4-7ce74963552a"
        paymentType:
          type: string
          example: "CARD"
        status:
          type: string
          example: "PAYMENT_PENDING"
    deliveryAddress:
      type: object
      properties:
        addressIdfier:
          type: string
          example: "UNIQUE_ADDRESS_001"
        addressLine1:
          type: string
          example: "123 Example St"
        addressLine2:
          type: string
          example: ""
        fullName:
          type: string
          example: "John Doe"
        phoneNo:
          type: string
          example: "+66910396309"
        city:
          type: string
          example: "Pathum Thani"
        state:
          type: string
          example: "string"
        country:
          type: string
          example: "Countryland"
        zipCode:
          type: string
          example: "12130"
        subDistrictCode:
          type: string
          example: "130601"
        subDistrictName:
          type: string
          example: "Tambon Khu Khot"
        districtCode:
          type: string
          example: "1306"
        districtName:
          type: string
          example: "Amphoe Lam Luk Ka"
        additionalPhoneNo:
          type: string
          example: "string"
        landmark:
          type: string
          example: "Near the central mall"
        addressType:
          type: string
          example: "Home"
        alternateAddress:
          type: string
          example: "string"    


    errorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            required: ["title", "message"]
            properties:
              title:
                type: string
              message:
                type: string
    ippData:
      type: object
      description: "this object will appear if quotation meet ipp criteria"
      properties:
        descriptions:
          type: array       
          items:
            type: object
            required:
              - isActive
              - bankCode
              - mdr
            properties:
              bankCode:
                type: string
                example: 123
              bankNameTh:
                type: string
                example: บัตรกรุงไทย จำกัด(มหาชน)
              bankNameEn:
                example:  Krungthai Card
              mdr:
                type: number
                format: double
                example: 3.3
              isActive:
                type: boolean
              ippLists:
                $ref: "#/components/schemas/ippDescriptionItem"
    ippDescriptionItem:
        type: object
        required:
          - id
          - term
          - minAmount
        properties:
          id:
            type: number
            example: 1
          term:
            type: number
            example: 4
          nocnocSub:
            type: boolean
          sellerSub:
            type: boolean
          title:
            type: string
            example: 4 เดือน
          minAmount:
            type: number
            example: 3000
    quotationSummaryRequest:
      type: object
      required:
        - quotationSignature
        - quotationData
        - sellers
      properties:
        quotationSignature:
          type: string
          example: hmac
        quotationData:
          type: string
          example: base64
        couponCodes:
          type: array
          items: 
            type: string
          example: [""]
        sellers:
          type: array
          items:
            type: object
            required:
            - id
            - saleOrders
            properties:
              id:
                type: number
              saleOrders:
                type: array
                items:
                  type: object
                  required:
                  - saleOrderRef
                  - defaultDeliveryOption
                  properties:
                    saleOrderRef:
                      type: string
                    defaultDeliveryOption:
                      type: object
                      required:
                        - carrierId
                      properties:
                        carrierId:
                          type: number
                          example: 12
        useNocnocPoint:
          type: boolean
          example: true
    quotationSummaryResponse:
      type: object
      required: ["data"]
      properties:
        data:
          type: object
          required: ["appliedPromotions", "totalPrice", "totalDiscount", "totalPriceAfterDiscount", "totalShippingFee", "totalShippingFeeAfterDiscount", "grandTotalDiscount", "grandTotal"]
          properties:
            quotationData:
              type: string
              example: <base64>
            quotationSignature:
              type: string
              example: <hmac>
            ipp:
              $ref: "#/components/schemas/ippData"
            coupons:
              type: array
              items:
                properties:
                  couponCode:
                    type: string
                    example: "NN1234"
                  limitApplies:
                    type: number
                    example: 1
                  type:
                    type: string
                    example: "NOCNOC_COUPON"
                  status:
                    type: string
                    enum: [VALID, NOTFOUND, ORDER_VALUE_NOT_REACH_MINIMUM]
                    example: "VALID"
            nocnocPoint:
              type: object
              properties:
                availablePoint:
                  type: number
                  example: 0
                isNocNocClubMember:
                  type: boolean
                  example: true
                pointBalance:
                  type: number
                  example: 0
                pointValue:
                  type: number
                  example: 0
            totalPrice:
              type: number
              example: 56300
            totalShopCouponDiscount:
              type: number
              example: 350
            totalPlatformDiscount:
              type: number
              example: 5630
            totalPartnerCouponDiscount:
              type: number
              example: 0
            totalVoucherDiscount:
              type: number
              example: 1000
            totalDiscount:
              type: number
              example: 6980
            totalNocnocPointDiscount:
              type: number
              example: 40
            totalPriceAfterDiscount:
              type: number
              example: 50320
            totalShippingFee:
              type: number
              example: 1770
            totalSellerShippingDiscount:
              type: number
              example: 10
            totalPlatformShippingDiscount:
              type: number
              example: 270
            totalShippingFeeAfterDiscount:
              type: number
              example: 280
            grandTotalDiscount:
              type: number
              example: 7300
            grandTotal:
              type: number
              example: 50770
            currency:
              type: string
              example: ฿
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: "JWT"
      
security:
  - bearer: []

